#!/usr/bin/with-contenv bashio
# =====================================================================
#  01-bootstrap.sh - Inicializa estado persistente del add-on:
#    1. SSH keypair en /data/.ssh (la pubkey se publica en logs y UI).
#    2. Ansible inventory dinamico desde options.json.
#    3. ansible.cfg apuntando a /data/.ssh.
#  Idempotente: si ya existe, no toca nada.
# =====================================================================
set -e

DATA="/data"
SSH_DIR="${DATA}/.ssh"
INV_DIR="${DATA}/ansible"
INV_FILE="${INV_DIR}/inventory.yml"
CFG_FILE="${INV_DIR}/ansible.cfg"

mkdir -p "${SSH_DIR}" "${INV_DIR}"
chmod 700 "${SSH_DIR}"

# 1) Keypair generation
if [ ! -f "${SSH_DIR}/id_ed25519" ]; then
    bashio::log.info "Generating fresh GOD Mode SSH keypair (ed25519)..."
    ssh-keygen -t ed25519 -N "" -f "${SSH_DIR}/id_ed25519" -C "god-mode@$(hostname)" >/dev/null
    chmod 600 "${SSH_DIR}/id_ed25519"
    chmod 644 "${SSH_DIR}/id_ed25519.pub"
fi

# 2) Persisted known_hosts
touch "${SSH_DIR}/known_hosts"
chmod 644 "${SSH_DIR}/known_hosts"

# 3) Mostrar pubkey en logs y guardar en /share para HA
PUB=$(cat "${SSH_DIR}/id_ed25519.pub")
bashio::log.info "==============================================================="
bashio::log.info "GOD Mode public SSH key:"
bashio::log.info "  ${PUB}"
bashio::log.info ""
bashio::log.info "Add it to ~/.ssh/authorized_keys on every host you want to"
bashio::log.info "monitor. From the add-on web UI you can copy/paste it directly."
bashio::log.info "==============================================================="

# Tambien copiamos a /config/god_mode_pubkey.txt para que el usuario
# lo encuentre rapido desde HA UI (Studio Code Server, FTP, etc)
if [ -d /config ]; then
    cp "${SSH_DIR}/id_ed25519.pub" /config/god_mode_pubkey.txt 2>/dev/null || true
fi

# 4) Render ansible inventory.yml desde options.json
HOSTS_JSON=$(bashio::config "hosts | tojson")
SSH_USER_DEFAULT=$(bashio::config "ssh_user" "root")

cat > "${INV_FILE}" <<INVHEADER
# AUTO-GENERATED by /etc/cont-init.d/01-bootstrap.sh on add-on start
# Edits will be lost. Modify hosts list in add-on Configuration UI.
all:
  vars:
    ansible_ssh_private_key_file: ${SSH_DIR}/id_ed25519
    ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=${SSH_DIR}/known_hosts -o ConnectTimeout=8'
    ansible_python_interpreter: auto_silent
  hosts:
INVHEADER

echo "${HOSTS_JSON}" | jq -c '.[]' | while IFS= read -r entry; do
    name=$(echo "${entry}" | jq -r '.name')
    addr=$(echo "${entry}" | jq -r '.addr')
    user=$(echo "${entry}" | jq -r --arg d "${SSH_USER_DEFAULT}" '.user // $d')
    port=$(echo "${entry}" | jq -r '.port // 22')
    {
        echo "    ${name}:"
        echo "      ansible_host: ${addr}"
        echo "      ansible_user: ${user}"
        echo "      ansible_port: ${port}"
    } >> "${INV_FILE}"
done

# 5) ansible.cfg
cat > "${CFG_FILE}" <<ANSCFG
[defaults]
inventory = ${INV_FILE}
host_key_checking = False
forks = 10
gathering = explicit
stdout_callback = json
callback_result_format = json
remote_tmp = /tmp/.ansible-\${USER:-root}/tmp
ANSCFG

# Export para los services
echo "ANSIBLE_CONFIG=${CFG_FILE}" >> /run/s6/container_environment/ANSIBLE_CONFIG
echo "${CFG_FILE}" > /run/s6/container_environment/ANSIBLE_CONFIG

bashio::log.info "Bootstrap complete. Inventory: ${INV_FILE}"
bashio::log.info "Hosts configured: $(echo "${HOSTS_JSON}" | jq 'length')"
